import type { Metadata } from "next";
import { Outfit } from 'next/font/google'
import "./globals.css";
import { MovieProvider } from '@/context/MovieContext';

// Font configuration
const outfit = Outfit({ 
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-outfit',
})

// Metadata configuration for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Single RootLayout component that combines both font configuration 
// and MovieProvider functionality
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Outfit font className to the body */}
      <body className={outfit.className}>
        {/* Wrap the entire application with MovieProvider for context access */}
        <MovieProvider>
          {children}
        </MovieProvider>
      </body>
    </html>
  );
}