import type { Metadata } from "next";
import { Outfit } from 'next/font/google'
import "./globals.css";

const outfit = Outfit({ 
  subsets: ['latin'],
  // Optional: specify weights you want to use
  weight: ['300', '400', '500', '600', '700'],
  // Optional: if you want to use it as a variable
  variable: '--font-outfit',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
      </body>
    </html>
  );
}
